// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOXv_N5hmDAgd99Sbt0nogVm23Kdtb9QE',
    appId: '1:8929213204:web:66c5cbc01d453d1c9fe001',
    messagingSenderId: '8929213204',
    projectId: 'givelocally-dev',
    authDomain: 'givelocally-dev.firebaseapp.com',
    databaseURL:
        'https://givelocally-dev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'givelocally-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4fZN8R3i1PvyYT4f03UMWU5oYB2UXIpU',
    appId: '1:8929213204:android:def4360a6374d72e9fe001',
    messagingSenderId: '8929213204',
    projectId: 'givelocally-dev',
    databaseURL:
        'https://givelocally-dev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'givelocally-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJpsFxj04WDfuF8hgfnS7ovzV7hMPMfd0',
    appId: '1:8929213204:ios:1265c0c97ce4a95f9fe001',
    messagingSenderId: '8929213204',
    projectId: 'givelocally-dev',
    databaseURL:
        'https://givelocally-dev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'givelocally-dev.appspot.com',
    iosBundleId: 'com.example.givelocallyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJpsFxj04WDfuF8hgfnS7ovzV7hMPMfd0',
    appId: '1:8929213204:ios:1265c0c97ce4a95f9fe001',
    messagingSenderId: '8929213204',
    projectId: 'givelocally-dev',
    databaseURL:
        'https://givelocally-dev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'givelocally-dev.appspot.com',
    iosBundleId: 'com.example.givelocallyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOXv_N5hmDAgd99Sbt0nogVm23Kdtb9QE',
    appId: '1:8929213204:web:edc41259711f20739fe001',
    messagingSenderId: '8929213204',
    projectId: 'givelocally-dev',
    authDomain: 'givelocally-dev.firebaseapp.com',
    databaseURL:
        'https://givelocally-dev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'givelocally-dev.appspot.com',
  );
}
